import Head from 'next/head';
import { useRouter } from 'next/router';

export default function Project() {
  const router = useRouter();
  const { slug } = router.query;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl">Project {slug}!</h1>
      </main>
    </>
  );
}
